from common_elements import get_element_by_text

brake_tire_battery_measurements = "xpath:" + get_element_by_text('Brake, Tire, & Battery Measurements')
select_mechanical_inspection = "xpath://a[contains(text(),'Mechanical Inspection')]"
mi_fail_button = "xpath:(" + get_element_by_text('Fail') + ")[2]"
mi_pass_button = "xpath:" + get_element_by_text('Pass')
select_measurement = "xpath://input[@name='picker']/../div[1]"
dmg_checkbox = "/../../../div[1]"
choose_action_enabled = "xpath://input[@placeholder='Choose Action' and not(@disabled)]/following-sibling::div[1]"
choose_severity_enabled = "xpath://div[@class='x-label x-layout-box-item x-flexed x-stretched']/div[1]"
labor_service_type = "xpath://input[@name='serviceTypeId']/../div[1]"
shop = "xpath://input[@name='siteShopId']/../div[1]"
labor_flat_fee = "xpath://input[@name='flatFeeId']/../div[1]"
labor_rate = "xpath://input[@name='laborRateId']/../div[1]"
labor_time = "xpath://input[@class='x-input-el x-form-field x-input-number' and @name='laborTime']"
labor_ext_price = "xpath://input[@name='laborExtendedPrice']/../../div[1]"
Reject_text = "xpath:" + get_element_by_text('Rejected')
Parts_needed = "xpath://input[@name='needsParts']"
Paint_labor = "xpath://div[@class='x-unsized x-button x-button-xtime']//child::span[3]"
Paint_labor_dialog = "xpath://div[@class='x-innerhtml' and text()='New Paint Labor']"


# mechanical inspection
ecr_iframe = "xpath://*[@id='ext-container-44']"  #cr damage dailog box
ecr_message_frame = "xpath://div[@class='x-container title x-layout-box-item x-stretched']"  #for crdamage dailog box
ecr_message = "xpath://div[contains(text(),'CR damage information not imported or no damages w')]" # for verifying message
ecr_popup = "id:ext-popup-1"  # no use
click_ok_button = "xpath://span[contains(text(),'OK')]" # ok in dialog box
search_tasks = "xpath://input[@placeholder='Search Tasks']"
click_search = "xpath://span[@class='x-button-icon x-shown icon-search']"
click_sub_task_description = "xpath://div[@class='subtask-description']"
select_fail = "xpath://span[@class='x-button-label'][contains(text(),'Fail')]"
mi_top_link = "xpath://div[contains(text(),'Mechanical Inspection')]"
div_Test_drive = "xpath:(//div[(text() = 'Inspection Tasks' or . = 'Inspection Tasks')])[1]"
span_Pass1 = "xpath:(" + get_element_by_text('Pass')+")[1]"
span_Pass2 = "xpath:(" + get_element_by_text('Pass')+")[2]"
span_Pass3 = "xpath:(" + get_element_by_text('Pass')+")[3]"
span_Pass4 = "xpath:(" + get_element_by_text('Pass')+")[4]"
span_Pass5 = "xpath:(" + get_element_by_text('Pass')+")[5]"
span_Pass6 = "xpath:(" + get_element_by_text('Pass')+")[6]"
span_Pass7 = "xpath:(" + get_element_by_text('Pass')+")[7]"
span_Pass8 = "xpath:(" + get_element_by_text('Pass')+")[8]"
span_Pass9 = "xpath:(" + get_element_by_text('Pass')+")[9]"
span_Pass10 = "xpath:(" + get_element_by_text('Pass')+")[10]"
span_Pass11 = "xpath:(" + get_element_by_text('Pass')+")[11]"
span_Pass12 = "xpath:(" + get_element_by_text('Pass')+")[12]"
span_Pass13 = "xpath:(" + get_element_by_text('Pass')+")[13]"
span_Pass14 = "xpath:(" + get_element_by_text('Pass')+")[14]"
span_Pass15 = "xpath:(" + get_element_by_text('Pass')+")[15]"
span_Pass16 = "xpath:(" + get_element_by_text('Pass')+")[16]"
span_Pass17 = "xpath:(" + get_element_by_text('Pass')+")[17]"
span_Pass18 = "xpath:(" + get_element_by_text('Pass')+")[18]"
span_Pass19 = "xpath:(" + get_element_by_text('Pass')+")[19]"
span_Pass20 = "xpath:(" + get_element_by_text('Pass')+")[20]"
span_Pass21 = "xpath:(" + get_element_by_text('Pass')+")[21]"
span_Pass22 = "xpath:(" + get_element_by_text('Pass')+")[22]"
span_Pass23 = "xpath:(" + get_element_by_text('Pass')+")[23]"
span_Pass24 = "xpath:(" + get_element_by_text('Pass')+")[24]"
span_Pass25 = "xpath:(" + get_element_by_text('Pass')+")[25]"
span_Pass26 = "xpath:(" + get_element_by_text('Pass')+")[26]"
span_Pass27 = "xpath:(" + get_element_by_text('Pass')+")[27]"
span_Pass28 = "xpath:(" + get_element_by_text('Pass')+")[28]"

span_Yes1 = "xpath:(" + get_element_by_text('Yes') + ")[1]"
span_Yes2 = "xpath:(" + get_element_by_text('Yes') + ")[2]"
span_Yes3 = "xpath:(" + get_element_by_text('Yes') + ")[3]"
span_Yes4 = "xpath:(" + get_element_by_text('Yes') + ")[4]"
span_Yes5 = "xpath:(" + get_element_by_text('Yes') + ")[5]"
span_Yes6 = "xpath:(" + get_element_by_text('Yes') + ")[6]"
span_Yes7 = "xpath:(" + get_element_by_text('Yes') + ")[7]"
span_Yes8 = "xpath:(" + get_element_by_text('Yes') + ")[8]"
span_Pass1 = "xpath:(" + get_element_by_text('Pass') + ")[1]"
span_Pass2 = "xpath:(" + get_element_by_text('Pass') + ")[2]"
span_complete_testdrive = "xpath:(" + get_element_by_text('Complete') + ")[3]"
span_complete_MI = "xpath:(//span[(text() = 'Complete' or . = 'Complete')])[1]"
span_confirm_MI_complete = "xpath:(//*[(text() = 'Yes' or . = 'Yes')])[2]"
div_AirSuspension_Observation = "xpath://div[(text() = 'Air Suspension')]"
div_Hood_Observation = "xpath:(//div[contains(text(),'Hood')])[1]"
div_FailObservation = "xpath:(//span[(text() = 'Fail' or . = 'Fail')])[2]"
div_Recommendation_Bent = "xpath:(//div[@class = 'x-field-mask'])[4]"
Dropdown_ChooseAction = "xpath:(//div[@class = 'x-field-mask'])[6]"
span_ChooseReplace = "xpath:" + get_element_by_text('Replace')
span_ChooseDiagnose = "xpath://span[contains(text(),'Diagnose')]"
button_SaveDamage = "xpath:" + get_element_by_text('Save')
div_EnterLaborTime = "xpath://input[@name = 'laborTime']"
div_LaborDetails_Service_Type = "xpath:(//form/div/div[2]/div[2]/div/div)[1]"
div_LaborDetails_ST_MECHLabor = "xpath:" + get_element_by_text('MECHANICAL LABOR')
div_LaborDetails_ST_DiagnoseLabor = "xpath://span[contains(text(),'Diagnose')]"
div_MI_Banner = "xpath:(//div[(text() = 'Mechanical Inspection>' or . = 'Mechanical Inspection>')])[2]"
div_ConditionSummary = "xpath:" + get_element_by_text('Condition Summary')
div_AirSuspension_Damage_CS = "xpath://div[text() = 'Air Suspension']"
button_EditDamage = "xpath:(.//*[normalize-space(text()) and normalize-space(.)='Replace Air Suspension'])[1]/following::div[15]"
button_MIWorkOrder = "xpath://a[contains(text(),'Mechanical Inspection')]"
div_FailNumber = "xpath://*[contains(text(),'Fail')]//following-sibling::span"
button_ImportCR_OK = "xpath://*[contains(text(),'OK')]"
button_ImportCR = "xpath://*[contains(text(),'Import CR')]"


div_CR1 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[1]/div/div[1]/div/div[1]/div/div"
div_CR2 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[2]/div/div[1]/div/div[1]/div/div"
div_CR3 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[3]/div/div[1]/div/div[1]/div/div"
div_CR4 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[4]/div/div[1]/div/div[1]/div/div"
div_CR5 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[5]/div/div[1]/div/div[1]/div/div"
div_CR6 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[6]/div/div[1]/div/div[1]/div/div"
div_CR7 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[7]/div/div[1]/div/div[1]/div/div"
div_CR8 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[8]/div/div[1]/div/div[1]/div/div"
div_CR9 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[9]/div/div[1]/div/div[1]/div/div"
div_CR10 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[10]/div/div[1]/div/div[1]/div/div"
div_CR11 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[11]/div/div[1]/div/div[1]/div/div"
div_CR12 = "xpath://div[@class='x-container x-unsized x-paint-monitored mechanical-inspection-task-list']/div/div[12]/div/div[1]/div/div[1]/div/div"
