APPROVER_ID = "approverId"
APPROVED_WORK = "approvedWork"
AUCTION_ID = "auctionId"
CHARGE_KEY = "chargeKey"
CUSTOMER = "customer"
EXPENSE_CODE = "expenseCode"
IGNORE_EXCEPTIONS = ("ConditionalCheckFailedException",)
REPAIR_COST_CENTER = "repairCostCenter"
REPAIR_COST_CENTER_ENUM = ("MVS", "Shared Services", "Sublet")
RETRY_EXCEPTIONS = ("ProvisionedThroughputExceededException", "ThrottlingException")
REQUIRED_CHARGES_STUB = "Charges record missing required field:"
REQUIRED_APPR_WORK_STUB = "Approved work object missing required field:"
SBLU = "sblu"
SERIAL_ID = "serialId"
SITE_ID = "site_id"
TOTAL_CHARGE = "totalCharge"
VALIDATOR_CHARGES_STUB = "Charges record has invalid"
VALIDATOR_APPR_WORK_STUB = "Approved work object has invalid"
VEHICLE_COMPLETE_FLAG = "vehicleCompleteFlag"
VIN = "vin"
WORK_ORDER = "workOrder"
WORK_ORDER_CREATE_DATE = "workOrderCreateDate"
WORK_ORDER_NUMBER = "work_order_number"
WORK_ORDER_KEY = "work_order_key"
SUBSCRIBER_SCOPE = "wholesale-accnt.events.subs.trusted.write"

EXISTING_MASHERY_EVENT_TYPES = [
    "VEHICLELIFECYCLE.BATTERYCHARGING.UPDATED",
    "PEDASHBOARD.LABOR.FEE.STATUS.COMPLETE",
    "PEDASHBOARD.LABOR.FEE.STATUS.UNDONE",
    "VEHICLELIFECYCLE.LABEL.UPDATED",
    "ORDERS.IMAGING.CREATED",
    "ORDERS.IMAGING.UPDATED",
    "UNITS.CREATED",
    "UNITS.UPDATED",
    "VEHICLECONSIGNMENT.CHECKEDIN",
    "ORDERS.CERTIFICATION.CREATED",
    "ORDERS.CERTIFICATION.UPDATED",
    "ORDERS.APPROVAL.COMPLETED",
    "ORDERS.RETAILRECON.UPDATED",
    "PEDASHBOARD.LABOR.CONDITION.STATUS.COMPLETE",
    "PEDASHBOARD.LABOR.CONDITION.STATUS.UNDONE",
    "VEHICLELIFECYCLE.VEHICLERELEASE.UPDATED",
    "VEHICLELIFECYCLE.EXERCISE.UPDATED",
    "ORDERS.CAPTURE.UPDATED",
    "OFFERINGS.CREATED",
    "OFFERINGS.UPDATED",
    "LOCATION.LOT.UPDATED",
    "DESIGNATED.DESCRIPTION.CREATED",
    "DESIGNATED.DESCRIPTION.UPDATED",
    "CHARGES.ORDERS.UPDATED",
    "CONSIGNMENTS.CREATED",
    "CONSIGNMENTS.UPDATED",
    "WORKCREDIT.RETAILRECON.UPDATED",
    "WORKCREDITFEE.RETAILRECON.UPDATED",
    "ORDERS.CONDITION.CREATED",
    "ORDERS.CONDITION.UPDATED",
    "ORDERS.DETAIL.CREATED",
    "ORDERS.DETAIL.UPDATED",
    "VEHICLELIFECYCLE.SERVICE.UPDATED",
    "VEHICLELIFECYCLE.VEHICLERELEASE.UPDATED",
    "PEDASHBOARD.LABOR.CONDITION.WORKCREDIT.UPDATE",
    "PEDASHBOARD.LABOR.FEE.WORKCREDIT.UPDATE",
    "VEHICLELIFECYCLE.INSPECTION.UPDATED",
    "CONSIGNMENT.BUYER_CONSIGNMENT_CHANGED",
    "CONSIGNMENT.BUYER_CONSIGNMENT_PAYMENT_CHANGED",
    "COMPLETEFEE.RETAILRECON.COMPLETED",
    "COMPLETEFEE.RETAILRECON.UNDONE",
    "COMPLETELABOR.RETAILRECON.COMPLETED",
    "COMPLETELABOR.RETAILRECON.UNDONE",
    "charges",
]

CIP_PUBLISH_EVENTS_SCOPE = "wholesale-accnt.events.expand.read wholesale-accnt.events.matched.write wholesale-accnt.events.subs.trusted.write"
CIP_EXPAND_SCOPE = "wholesale-accnt.events.expand.read"
